---
title: "Group 11 Workshop 3"
description: "3rd Homework within Applied Statistics with R class"
slug: homework3
image: team3.jpg
keywords: ""
categories: 
    - ""
    - ""
date: 2022-09-12
draft: false
---



<div id="youth-risk-behavior-surveillance" class="section level1">
<h1>Youth Risk Behavior Surveillance</h1>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<p>Using visualization and summary statistics, describe the distribution of weights. How many observations are we missing weights from? Use also the skim function.</p>
<pre class="r"><code>data(yrbss)

# Create summary statistics
summary(yrbss$weight)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##      30      56      64      68      76     181    1004</code></pre>
<pre class="r"><code>skimr::skim(yrbss)</code></pre>
<table>
<caption>(#tab:eda_on_weight)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">yrbss</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">13583</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">13</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">8</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table style="width:100%;">
<colgroup>
<col width="30%" />
<col width="12%" />
<col width="16%" />
<col width="4%" />
<col width="4%" />
<col width="7%" />
<col width="10%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gender</td>
<td align="right">12</td>
<td align="right">1.00</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">grade</td>
<td align="right">79</td>
<td align="right">0.99</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hispanic</td>
<td align="right">231</td>
<td align="right">0.98</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">2805</td>
<td align="right">0.79</td>
<td align="right">5</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">helmet_12m</td>
<td align="right">311</td>
<td align="right">0.98</td>
<td align="right">5</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">text_while_driving_30d</td>
<td align="right">918</td>
<td align="right">0.93</td>
<td align="right">1</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hours_tv_per_school_day</td>
<td align="right">338</td>
<td align="right">0.98</td>
<td align="right">1</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">school_night_hours_sleep</td>
<td align="right">1248</td>
<td align="right">0.91</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table style="width:100%;">
<colgroup>
<col width="22%" />
<col width="10%" />
<col width="15%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="5%" />
<col width="6%" />
<col width="6%" />
<col width="7%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">77</td>
<td align="right">0.99</td>
<td align="right">16.16</td>
<td align="right">1.26</td>
<td align="right">12.00</td>
<td align="right">15.0</td>
<td align="right">16.00</td>
<td align="right">17.00</td>
<td align="right">18.00</td>
<td align="left">▁▂▅▅▇</td>
</tr>
<tr class="even">
<td align="left">height</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">1.69</td>
<td align="right">0.10</td>
<td align="right">1.27</td>
<td align="right">1.6</td>
<td align="right">1.68</td>
<td align="right">1.78</td>
<td align="right">2.11</td>
<td align="left">▁▅▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">weight</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">67.91</td>
<td align="right">16.90</td>
<td align="right">29.94</td>
<td align="right">56.2</td>
<td align="right">64.41</td>
<td align="right">76.20</td>
<td align="right">180.99</td>
<td align="left">▆▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">physically_active_7d</td>
<td align="right">273</td>
<td align="right">0.98</td>
<td align="right">3.90</td>
<td align="right">2.56</td>
<td align="right">0.00</td>
<td align="right">2.0</td>
<td align="right">4.00</td>
<td align="right">7.00</td>
<td align="right">7.00</td>
<td align="left">▆▂▅▃▇</td>
</tr>
<tr class="odd">
<td align="left">strength_training_7d</td>
<td align="right">1176</td>
<td align="right">0.91</td>
<td align="right">2.95</td>
<td align="right">2.58</td>
<td align="right">0.00</td>
<td align="right">0.0</td>
<td align="right">3.00</td>
<td align="right">5.00</td>
<td align="right">7.00</td>
<td align="left">▇▂▅▂▅</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Plot missing values
kable(yrbss%&gt;%
  filter(is.na(weight))%&gt;%
  summarise(Toatal_missing_data=n()),&quot;simple&quot;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">Toatal_missing_data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1004</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Create histogram
x &lt;- yrbss$weight 
h&lt;-hist(x,  
        xlab=&quot;weight&quot;, main=&quot;Histogram with Normal Curve&quot;) 

# Create normal distribution as comparison
xfit&lt;-seq(min(x,na.rm = TRUE),max(x,na.rm = TRUE),length=40)               #  order the data 
yfit&lt;-dnorm(xfit,mean=mean(x,na.rm = TRUE),sd=sd(x,na.rm = TRUE))          #  density of normal dis
yfit &lt;- yfit*diff(h$mids[1:2])*length(x) 
lines(xfit, yfit, col=&quot;red&quot;, lwd=2) </code></pre>
<p><img src="/blogs/homework3_files/figure-html/eda_on_weight-1.png" width="648" style="display: block; margin: auto;" />
<strong>Answer:</strong><br />
</p>
<p>The minimum value of weight is 30, the maximum value is 181, the median is 64, the lower quantile is 56, the upper quantile is 76, and the total number of missing values is 1004. The distribution of weights looks lightly skewed to the right. We added a normal distribution line as comparison.<br />
</p>
<p>Let’s create a new variable in the dataframe <code>yrbss</code>, called <code>physical_3plus</code> , which will be <code>yes</code> if they are physically active for at least 3 days a week, and <code>no</code> otherwise. Use the <code>count()</code> function and see if you get the same results as <code>group_by()... summarise()</code>. Also plot your data.</p>
<pre class="r"><code># Create new variable
yrbss$physical_3plus&lt;-ifelse(yrbss$physically_active_7d&gt;=3,&quot;yes&quot;,&quot;no&quot;)

# Method group_by()... summarise()
yrbss%&gt;%
  group_by(physical_3plus)%&gt;%
  summarise(n=n())%&gt;%
  mutate(prop=label_percent()(n/nrow(yrbss)))</code></pre>
<pre><code>## # A tibble: 3 × 3
##   physical_3plus     n prop 
##   &lt;chr&gt;          &lt;int&gt; &lt;chr&gt;
## 1 no              4404 32%  
## 2 yes             8906 66%  
## 3 &lt;NA&gt;             273 2%</code></pre>
<pre class="r"><code># Method count()
yrbss%&gt;%
count(physical_3plus) %&gt;% 
mutate(prop=label_percent()(n/nrow(yrbss)))</code></pre>
<pre><code>## # A tibble: 3 × 3
##   physical_3plus     n prop 
##   &lt;chr&gt;          &lt;int&gt; &lt;chr&gt;
## 1 no              4404 32%  
## 2 yes             8906 66%  
## 3 &lt;NA&gt;             273 2%</code></pre>
<pre class="r"><code># Create a graph to show difference
yrbss%&gt;%
  filter(is.na(physical_3plus)==FALSE)%&gt;%
  group_by(physical_3plus)%&gt;%
  summarise(number=n())%&gt;%
ggplot(aes(x=physical_3plus,y=number))+
  geom_bar(stat = &quot;identity&quot;,width =0.5)+
  labs(x=&quot;physical_3plus&quot;,y=&quot;number&quot;)+
  ggtitle(&quot;How many children workout 3plus times?&quot;,
          subtitle = &quot;&quot;)+
  theme_bw()</code></pre>
<p><img src="/blogs/homework3_files/figure-html/mutate_and_count-1.png" width="648" style="display: block; margin: auto;" />
<strong>Answer:</strong><br />
</p>
<p>In this first analysis we have separately shown the percentage proportion also for the NA values. 8906 kids practice sport 3plus times a week while 4404 do not. In the graph we have not included the NA values.</p>
</div>
<div id="confidence-interval-for-proportion-3plus" class="section level2">
<h2>Confidence Interval for Proportion 3plus</h2>
<p>Can you provide a 95% confidence interval for the population proportion of high schools that are <em>NOT</em> active 3 or more days per week?</p>
<pre class="r"><code>#Filtering data

test&lt;-yrbss %&gt;% 
  filter(is.na(physical_3plus)==FALSE)%&gt;%
  
# Changing yes no to numerical value to make it easier  
  mutate(physical_3_p=ifelse(physical_3plus==&quot;yes&quot;,1,0), physical_3_l=ifelse(physical_3plus==&quot;no&quot;,1,0))


# With formula

ci_yrbss &lt;- test %&gt;% 
  filter(!is.na(physical_3plus)) %&gt;%
  summarize(count = n(),
            p = (sum(physical_3plus == &quot;no&quot;))/count,
            t_critical = qt(0.975, count-1),
            se_diff = sqrt(p*(1-p)/count),
            margin_of_error = t_critical * se_diff,
            prop_low = p - margin_of_error,
            prop_high = p + margin_of_error)

# print the table with confidence interval

kable(ci_yrbss,
      caption=&quot;CI 3 or more times active Formula&quot;)</code></pre>
<table>
<caption>(#tab:confidence_interval)CI 3 or more times active Formula</caption>
<colgroup>
<col width="9%" />
<col width="9%" />
<col width="16%" />
<col width="12%" />
<col width="24%" />
<col width="13%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">count</th>
<th align="right">p</th>
<th align="right">t_critical</th>
<th align="right">se_diff</th>
<th align="right">margin_of_error</th>
<th align="right">prop_low</th>
<th align="right">prop_high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">13310</td>
<td align="right">0.331</td>
<td align="right">1.96</td>
<td align="right">0.004</td>
<td align="right">0.008</td>
<td align="right">0.323</td>
<td align="right">0.339</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Confidence Interval with bootstrap  

set.seed(1234)
boot_3lower &lt;- test %&gt;% 
# Select
  filter(is.na(physical_3plus)==FALSE)%&gt;%                  
# Specify the variable of interest
  specify(response = physical_3_l) %&gt;%
# Generate a bunch of bootstrap samples
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
  calculate(stat = &quot;mean&quot;) 

percentile_ci&lt;- boot_3lower %&gt;% 
   get_confidence_interval(level=0.95, type=&quot;percentile&quot;)
kable(percentile_ci,
      caption=&quot;CI 3 or more times active Infer&quot;)</code></pre>
<table>
<caption>(#tab:confidence_interval)CI 3 or more times active Infer</caption>
<thead>
<tr class="header">
<th align="right">lower_ci</th>
<th align="right">upper_ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.323</td>
<td align="right">0.338</td>
</tr>
</tbody>
</table>
<p><strong>Answer:</strong><br />
</p>
<p>The 95% confidence interval is [0.323,0.339] calculated with both, formula and bootstrap.</p>
</div>
<div id="boxplot-3plus" class="section level2">
<h2>Boxplot 3plus</h2>
<p>Make a boxplot of <code>physical_3plus</code> vs. <code>weight</code>. Is there a relationship between these two variables? What did you expect and why?</p>
<pre class="r"><code># Create boxplot

yrbss%&gt;%
  filter(is.na(physical_3plus)==FALSE)%&gt;%
ggplot(aes(x=physical_3plus,y=weight))+
  geom_boxplot()+
  ggtitle(&quot;The boxplot of the weight of physical_3plus&quot;,
          subtitle = &quot;&quot;)+
  theme_bw()</code></pre>
<p><img src="/blogs/homework3_files/figure-html/boxplot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p><strong>Answer:</strong><br />
</p>
<p>Although almost similiar, there is a positive relationship between being physically active for at least 3 days a week and weight. The result is somehow counter-intuitive, since we thought that more exercise in children would reduce there weight. This might be explained by the reason that people who stay highly active take part of physically demanding sports like basket, football and similiar and have thus a higher percentage of muscle or are just bigger. One additional reason could be that kids who are slightly heavier are more incentivised to exercise more frequently.</p>
</div>
<div id="confidence-interval-weight-by-formula" class="section level2">
<h2>Confidence Interval Weight by Formula</h2>
<p>Calculate the mean, SD, etc. weight in these groups using the mean function, we must ignore any missing values by setting the <code>na.rm = TRUE</code>and define confidence interval.</p>
<pre class="r"><code>#Apllying formula to weight
ci_yrbss_weight &lt;- yrbss %&gt;% 
  filter(is.na(physical_3plus)==FALSE)%&gt;%
  group_by(physical_3plus) %&gt;% 
  summarize(mean = mean(weight, na.rm=TRUE),
            sd = sd(weight, na.rm=TRUE),
            count = n(),
            t_critical = qt(0.975, count-1),
            se_diff = sd/sqrt(count),
            margin_of_error = t_critical * se_diff,
            weight_low = mean - margin_of_error,
            weight_high = mean + margin_of_error)

#Plotting results
kable(ci_yrbss_weight)</code></pre>
<table>
<colgroup>
<col width="16%" />
<col width="5%" />
<col width="5%" />
<col width="6%" />
<col width="12%" />
<col width="8%" />
<col width="17%" />
<col width="12%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">physical_3plus</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">count</th>
<th align="right">t_critical</th>
<th align="right">se_diff</th>
<th align="right">margin_of_error</th>
<th align="right">weight_low</th>
<th align="right">weight_high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">no</td>
<td align="right">66.7</td>
<td align="right">17.6</td>
<td align="right">4404</td>
<td align="right">1.96</td>
<td align="right">0.266</td>
<td align="right">0.521</td>
<td align="right">66.2</td>
<td align="right">67.2</td>
</tr>
<tr class="even">
<td align="left">yes</td>
<td align="right">68.4</td>
<td align="right">16.5</td>
<td align="right">8906</td>
<td align="right">1.96</td>
<td align="right">0.175</td>
<td align="right">0.342</td>
<td align="right">68.1</td>
<td align="right">68.8</td>
</tr>
</tbody>
</table>
<p>There is an observed mean difference of about 1.77kg (68.44 - 66.67), and we notice that the two confidence intervals do not overlap. It seems that the difference is statistically significant at 95% confidence. Let us however also conduct a hypothesis test.</p>
</div>
<div id="hypothesis-test-with-formula" class="section level2">
<h2>Hypothesis test with formula</h2>
<p>Write the null and alternative hypotheses for testing whether mean weights are different for those who exercise at least times a week and those who don’t.<br />
</p>
<p><strong>Answer:</strong><br />
</p>
<p>Null Hypothesis: mean weights are same for those who exercise at least 3 times a week and those who don’t.<br />
</p>
<p>Alternative hypotheses: mean weights are not same for those who exercise at least times a week and those who don’t.<br />
</p>
<p>From the calculation below and the output of t.test, confidence interval and p-value , we can infer that the Null Hypothesis can be rejected and alternative hypotheses accepted.</p>
<pre class="r"><code>t.test(weight ~ physical_3plus, data = yrbss)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = -5, df = 7479, p-value = 9e-08
## alternative hypothesis: true difference in means between group no and group yes is not equal to 0
## 95 percent confidence interval:
##  -2.42 -1.12
## sample estimates:
##  mean in group no mean in group yes 
##              66.7              68.4</code></pre>
</div>
<div id="hypothesis-test-with-infer" class="section level2">
<h2>Hypothesis test with <code>infer</code></h2>
<p>First, we need to initialize the test, which we will save as <code>obs_diff</code>.</p>
<pre class="r"><code>yrbss_filtered&lt;-yrbss%&gt;%
  filter(is.na(physical_3plus)==FALSE,is.na(weight)==FALSE)

obs_diff &lt;- yrbss_filtered %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))

obs_diff</code></pre>
<pre><code>## Response: weight (numeric)
## Explanatory: physical_3plus (factor)
## # A tibble: 1 × 1
##    stat
##   &lt;dbl&gt;
## 1  1.77</code></pre>
<p>After you have initialized the test, you need to simulate the test on the null distribution, which we will save as null.</p>
<pre class="r"><code>null_dist &lt;- yrbss_filtered %&gt;%
  # specify variables
  specify(weight ~ physical_3plus) %&gt;%
  
  # assume independence, i.e, there is no difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  # generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  
  # calculate statistic of difference, namely &quot;diff in means&quot;
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>We can visualize this null distribution with the following code:</p>
<pre class="r"><code>ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram()</code></pre>
<p><img src="/blogs/homework3_files/figure-html/unnamed-chunk-1-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>We can also calculate the p-value for your hypothesis test using the function <code>infer::get_p_value()</code>.</p>
<pre class="r"><code>null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/blogs/homework3_files/figure-html/unnamed-chunk-2-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
</div>
</div>
<div id="imdb-ratings-differences-between-directors" class="section level1">
<h1>IMDB ratings: Differences between directors</h1>
<div id="reproduce-the-following-graph" class="section level2">
<h2>Reproduce the following graph</h2>
<p><img src="../../images/directors.png" width="100%" style="display: block; margin: auto;" />
Loading data:</p>
<pre class="r"><code>movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))</code></pre>
<p>Calculating confidence intervals:</p>
<pre class="r"><code># Filtering data for directors
movies&lt;-movies%&gt;%
  filter(director %in% c(&quot;Steven Spielberg&quot;, &quot;Tim Burton&quot;))

#director==&quot;Steven Spielberg&quot;,mean=7.57 ,the 95% confidence interval is [7.27,7.87]
a&lt;-movies%&gt;%
  filter(director==&quot;Steven Spielberg&quot;)
t.test(a$rating)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  a$rating
## t = 52, df = 22, p-value &lt;2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  7.27 7.87
## sample estimates:
## mean of x 
##      7.57</code></pre>
<pre class="r"><code>#director==&quot;Tim Burton&quot;,mean=6.93 ,the 95% confidence interval is [6.53,7.33]
b&lt;-movies%&gt;%
  filter(director==&quot;Tim Burton&quot;)
t.test(b$rating)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  b$rating
## t = 37, df = 15, p-value = 4e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  6.53 7.33
## sample estimates:
## mean of x 
##      6.93</code></pre>
<pre class="r"><code>df &lt;- tibble(
  director = c(&quot;Steven Spielberg&quot;,&quot;Tim Burton&quot;),
  mean = c(7.57, 6.93),
  lower = c( 7.27,6.53),
  upper = c( 7.87, 7.33)
) %&gt;% 
  map_df(rev)


options(ggplot2.discrete.colour= c(&quot;#F8766D&quot;, &quot;#00BFC4&quot;))

p &lt;- ggplot(data = df,aes(color = director))
p+geom_errorbarh(aes(y=forcats::fct_inorder(director),xmin=lower,xmax=upper),
                 height=0.1,
                 size=1.5)+
  #geom_text(aes(label=VAL),size=4,Vjust=-0.5)+
  geom_text(aes(label = mean, x = mean, y = director), vjust = -1.5, size=6, color = &quot;black&quot;) +
  geom_text(aes(label = lower, x = lower, y = director), vjust = -2.5, size=4, color = &quot;black&quot;) +
  geom_text(aes(label = upper, x = upper, y = director), vjust = -2.5, size=4, color = &quot;black&quot;) +
  geom_point(aes(x=mean,y=director),size=5)+
  theme_bw()+
  ggtitle(&quot;Do Spielberg and Burton have the same mean IMDB ratings&quot;,
          subtitle = &quot;95% confidence intercals overlap&quot;)+
  theme(legend.position = &quot;none&quot;)+
  xlab(&quot;Mean IMBD Rating&quot;)+
  ylab(&quot;&quot;)+
  geom_rect(aes(xmin=7.271, xmax=7.311, ymin=-Inf, ymax=Inf), color = NA,alpha = .1)</code></pre>
<p><img src="/blogs/homework3_files/figure-html/unnamed-chunk-3-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="hypothesis-testing" class="section level2">
<h2>Hypothesis testing</h2>
<p>In addition, you will run a hypothesis test. You should use both the <code>t.test</code> command and the <code>infer</code> package to simulate from a null distribution, where you assume zero difference between the two.</p>
<p><strong>Answer:</strong><br />
</p>
<p>Null hypotheses:the mean IMDB rating for Steven Spielberg and Tim Burton are the same .<br />
Alternative hypotheses:the mean IMDB rating for Steven Spielberg and Tim Burton are not the same .<br />
</p>
<p>Using the t-test:</p>
<pre class="r"><code>t.test(rating ~ director, data = movies)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  rating by director
## t = 3, df = 31, p-value = 0.01
## alternative hypothesis: true difference in means between group Steven Spielberg and group Tim Burton is not equal to 0
## 95 percent confidence interval:
##  0.16 1.13
## sample estimates:
## mean in group Steven Spielberg       mean in group Tim Burton 
##                           7.57                           6.93</code></pre>
<p>Using the infer package:<br />
</p>
<pre class="r"><code># Calculate diff in means

obs_diff &lt;- movies %&gt;%
  specify(rating ~ director) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;Steven Spielberg&quot;,&quot;Tim Burton&quot;))


# Infer package

null_dist &lt;- movies %&gt;%
  # specify variables
  specify(rating ~ director) %&gt;%
  
  # assume independence, i.e, there is no difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  # generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  
  # calculate statistic of difference, namely &quot;diff in means&quot;
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;Steven Spielberg&quot;,&quot;Tim Burton&quot;))

# Plot the relevant values

null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)+
  theme_bw()</code></pre>
<p><img src="/blogs/homework3_files/figure-html/hypothesis_testing_with_infer_package-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1   0.012</code></pre>
<p><strong>Answer:</strong><br />
</p>
<p>Both the formula as well as the infer approach showed (p-value &lt; 5% etc.) that we can reject the null hypothesis. At the end of the day we thus conclude that indeed the true difference in means between Steven Spielberg Movies and Tim Burton Movies is not equal to 0.</p>
</div>
</div>
<div id="omega-group-plc--pay-discrimination" class="section level1">
<h1>Omega Group plc- Pay Discrimination</h1>
<p>You are asked to carry out the analysis. The objective is to find out whether there is indeed a significant difference between the salaries of men and women, and whether the difference is due to discrimination or whether it is based on another, possibly valid, determining factor.</p>
<p>Loading the data:</p>
<pre class="r"><code>omega &lt;- read_csv(here::here(&quot;data&quot;, &quot;omega.csv&quot;))
glimpse(omega) # examine the data frame</code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, 635…
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;ma…
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24, 3…</code></pre>
<div id="relationship-salary---gender" class="section level2">
<h2>Relationship Salary - Gender ?</h2>
<pre class="r"><code># Summary Statistics of salary by gender
kable(favstats (salary ~ gender, data=omega))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">gender</th>
<th align="right">min</th>
<th align="right">Q1</th>
<th align="right">median</th>
<th align="right">Q3</th>
<th align="right">max</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">n</th>
<th align="right">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">female</td>
<td align="right">47033</td>
<td align="right">60338</td>
<td align="right">64618</td>
<td align="right">70033</td>
<td align="right">78800</td>
<td align="right">64543</td>
<td align="right">7567</td>
<td align="right">26</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">male</td>
<td align="right">54768</td>
<td align="right">68331</td>
<td align="right">74675</td>
<td align="right">78568</td>
<td align="right">84576</td>
<td align="right">73239</td>
<td align="right">7463</td>
<td align="right">24</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Dataframe with two rows (male-female) and having as columns gender, mean, SD, sample size, 
# the t-critical value, the standard error, the margin of error, 
# and the low/high endpoints of a 95% condifence interval

ci_omega &lt;- omega %&gt;% 
  group_by(gender) %&gt;% 
  summarize(mean = mean(salary, na.rm=TRUE),
            sd = sd(salary, na.rm=TRUE),
            count = n(),
            t_critical = qt(0.975, count-1),
            se_diff = sd/sqrt(count),
            margin_of_error = t_critical * se_diff,
            salary_low = mean - margin_of_error,
            salary_high = mean + margin_of_error)

# print the table with confidence interval

kable(ci_omega,
      caption=&quot;Salary CI by Gender&quot;)</code></pre>
<table>
<caption>(#tab:confint_single_valiables)Salary CI by Gender</caption>
<colgroup>
<col width="8%" />
<col width="7%" />
<col width="6%" />
<col width="7%" />
<col width="13%" />
<col width="9%" />
<col width="19%" />
<col width="13%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">gender</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">count</th>
<th align="right">t_critical</th>
<th align="right">se_diff</th>
<th align="right">margin_of_error</th>
<th align="right">salary_low</th>
<th align="right">salary_high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">female</td>
<td align="right">64543</td>
<td align="right">7567</td>
<td align="right">26</td>
<td align="right">2.06</td>
<td align="right">1484</td>
<td align="right">3056</td>
<td align="right">61486</td>
<td align="right">67599</td>
</tr>
<tr class="even">
<td align="left">male</td>
<td align="right">73239</td>
<td align="right">7463</td>
<td align="right">24</td>
<td align="right">2.07</td>
<td align="right">1523</td>
<td align="right">3151</td>
<td align="right">70088</td>
<td align="right">76390</td>
</tr>
</tbody>
</table>
<p>What can you conclude from your analysis? A couple of sentences would be enough</p>
<p><strong>Answer:</strong><br />
The two confidence interval for women and men salary of a 95% do not overlap. The difference in salary between the two groups is thus significantly different. The t-test would thus not be needed in this case.</p>
</div>
<div id="relationship-salary---gender-hypothesis-test-t.test-infer" class="section level2">
<h2>Relationship Salary - Gender Hypothesis Test (t.test + infer)</h2>
<pre class="r"><code># hypothesis testing using t.test() 

t.test(salary ~ gender, data = omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  salary by gender
## t = -4, df = 48, p-value = 2e-04
## alternative hypothesis: true difference in means between group female and group male is not equal to 0
## 95 percent confidence interval:
##  -12973  -4420
## sample estimates:
## mean in group female   mean in group male 
##                64543                73239</code></pre>
<pre class="r"><code># hypothesis testing using infer package

#Calculating observed statistic
obs_stat &lt;- omega %&gt;%
  specify(salary ~ gender) %&gt;%
  calculate(stat = &quot;diff in means&quot;,
            order = c(&quot;female&quot;, &quot;male&quot;))

set.seed(1234)
salaries_in_null_world &lt;- omega %&gt;% 
  
  #Which variable we are interested in
  specify(salary ~ gender) %&gt;% 
  
  #Hypothesis with no (null) difference
  hypothesize(null = &quot;independence&quot;) %&gt;% 
  
  #Create simulated samples
  generate(reps = 10000, type = &quot;permute&quot;) %&gt;% 
  
  #Mean difference in each sample
  calculate(stat = &quot;diff in means&quot;,
            order = c(&quot;female&quot;, &quot;male&quot;)) # give the order for subtraction first, second

#Visualize distribution  
salaries_in_null_world %&gt;% visualize()+
  shade_p_value(obs_stat = obs_stat, direction = &quot;both&quot;) </code></pre>
<p><img src="/blogs/homework3_files/figure-html/hypothesis_testing-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>salaries_in_null_world %&gt;% 
  get_p_value(obs_stat = obs_stat, direction = &quot;both&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1  0.0002</code></pre>
<p>What can you conclude from your analysis? A couple of sentences would be enough</p>
<p><strong>Answer</strong>:<br />
</p>
<p>The R t-test clearly showed that the null hypothesis (no difference) can be rejected. This can be seen by three indicators: first the |t-stat| is approximately &gt; 2, second the CI for delta does not contain zero, third the p-value is &lt; 5%.<br />
With 1000 reps the bootstrap simulation gave a p-value of zero, this can be the case when the observed statistic is very unlikely. We thus had to increase the reps to 10000 to replicate the results from the formula.</p>
</div>
<div id="relationship-experience---gender" class="section level2">
<h2>Relationship Experience - Gender?</h2>
<pre class="r"><code># Summary Statistics of salary by gender
favstats (experience ~ gender, data=omega)</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0</code></pre>
<p>Based on this evidence, can you conclude that there is a significant difference between the experience of the male and female executives? Does your conclusion validate or endanger your conclusion about the difference in male and female salaries?</p>
<pre class="r"><code>#Using formula to create confidence interval

ci_omega_experience &lt;- omega %&gt;% 
  group_by(gender) %&gt;% 
  summarize(mean = mean(experience, na.rm=TRUE),
            sd = sd(experience, na.rm=TRUE),
            count = n(),
            t_critical = qt(0.975, count-1),
            se_diff = sd/sqrt(count),
            margin_of_error = t_critical * se_diff,
            experience_low = mean - margin_of_error,
            experience_high = mean + margin_of_error)

# print the table with confidence interval

kable(ci_omega_experience,
      caption=&quot;Experience CI by Gender&quot;)</code></pre>
<table>
<caption>(#tab:ci_experience)Experience CI by Gender</caption>
<colgroup>
<col width="7%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="12%" />
<col width="8%" />
<col width="17%" />
<col width="16%" />
<col width="17%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">gender</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">count</th>
<th align="right">t_critical</th>
<th align="right">se_diff</th>
<th align="right">margin_of_error</th>
<th align="right">experience_low</th>
<th align="right">experience_high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">female</td>
<td align="right">7.38</td>
<td align="right">8.51</td>
<td align="right">26</td>
<td align="right">2.06</td>
<td align="right">1.67</td>
<td align="right">3.44</td>
<td align="right">3.95</td>
<td align="right">10.8</td>
</tr>
<tr class="even">
<td align="left">male</td>
<td align="right">21.12</td>
<td align="right">10.92</td>
<td align="right">24</td>
<td align="right">2.07</td>
<td align="right">2.23</td>
<td align="right">4.61</td>
<td align="right">16.52</td>
<td align="right">25.7</td>
</tr>
</tbody>
</table>
<p><strong>Answer:</strong><br />
</p>
<p>The two experience confidence intervals for women and men at 95% do not overlap. The difference between the two groups is thus significantly different and there is no need to run a t-test. These findings would endager the conclusion drawn above (gender-based salary discrimination) as it seems that not only gender, but an additional previously not considered factor, experience, could influence the pay-gap. Further anaylsis is suggested.</p>
</div>
<div id="relationship-salary---experience" class="section level2">
<h2>Relationship Salary - Experience ?</h2>
<p>Someone at the meeting argues that clearly, a more thorough analysis of the relationship between salary and experience is required before any conclusion can be drawn about whether there is any gender-based salary discrimination in the company.</p>
<p>Analyse the relationship between salary and experience. Draw a scatterplot to visually inspect the data</p>
<pre class="r"><code>ggplot(omega, aes(x = experience, y = salary, color = gender)) +
  geom_point()+
  geom_smooth(method=&#39;lm&#39;, se=FALSE)+
  labs(
    title = &quot;Relationship between salary and experience&quot;
  )+
  theme_bw()</code></pre>
<p><img src="/blogs/homework3_files/figure-html/salary_exp_scatter-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="check-correlations-between-gender-experience-and-salary" class="section level2">
<h2>Check correlations between Gender, Experience and Salary</h2>
<pre class="r"><code>omega %&gt;% 
  select(gender, experience, salary) %&gt;% #order variables they will appear in ggpairs()
  ggpairs(aes(colour=gender, alpha = 0.3))+
  theme_bw()</code></pre>
<p><img src="/blogs/homework3_files/figure-html/ggpairs-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Look at the salary vs experience scatterplot. What can you infer from this plot? Explain in a couple of sentences</p>
<p><strong>Answer:</strong><br />
</p>
<p>The correlation matrix reweals many interesting things in just one visualization. Looking at the scatterplot we can see a clear correlation between years of experience and salary, this is true for both genders. The correlation can also be confirmed mathematically with a total cor of 0.8. In other words, the higher the experience the higher the salary. We have used two colors in the plot above to demonstrate that women salary increase more significantly with growing experience (stepper slope). With women having a median experience of 3 and men of 19.5 it is thus not surprising that there is a significant pay-gap. Omega should rather investigate the underlying reason why women have so little work experience. Are senior positions which require more experience mainly filled by man while graduate positions mainly by women? Anyhow, further investigation is needed!</p>
</div>
</div>
<div id="challenge-1-brexit-plot" class="section level1">
<h1>Challenge 1: Brexit plot</h1>
<div id="reproduce-the-graph-shown-in-class-using-the-same-colors" class="section level2">
<h2>Reproduce the Graph shown in class using the same colors</h2>
<p>Import the data:</p>
<pre class="r"><code>brexit_results &lt;- read_csv(&quot;https://raw.githubusercontent.com/kostis-christodoulou/am01/master/data/brexit_results.csv&quot;)</code></pre>
<pre class="r"><code># Concatenated colors in new variable

parties_brexit_names &lt;- c(&quot;Conservative&quot;, &quot;Labour&quot;, &quot;Lib Dems&quot;, &quot;UKIP&quot;)
colors_brexit &lt;- c(&quot;#0087dc&quot;, &quot;#d50000&quot;,&quot;#FDBB30&quot;,&quot;#EFE600&quot;)

# Tidy long format

tidyresults &lt;- brexit_results %&gt;% 
  select(1:6) %&gt;% 
  pivot_longer(cols = 2:5,
               names_to = &quot;party&quot;,
               values_to = &quot;percentage&quot;) 

# Create scatterplot with regression lines

ggplot(tidyresults, aes(x= percentage, y = leave_share, colour = party)) +
  geom_point(alpha = 0.3, size = 1)+
  geom_smooth(method=lm)+
  labs(
    title = &quot;How political affiliation translated to Brexit Voting&quot;,
    y = &quot;Leave % in the 2016 Brexit referendum&quot;,
    x = &quot;Party % in the UK 2015 general election&quot;
  )+
  theme_bw()+
  ylim(20, 102)+
  theme(legend.position=&quot;bottom&quot;,
        legend.title = element_blank())+
  theme(text = element_text(size = 7))+
  scale_color_manual(values=colors_brexit,
                    labels=parties_brexit_names)</code></pre>
<p><img src="/blogs/homework3_files/figure-html/unnamed-chunk-6-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="challenge-2gdp-components-over-time-and-among-countries" class="section level1">
<h1>Challenge 2:GDP components over time and among countries</h1>
<pre class="r"><code>UN_GDP_data  &lt;-  read_excel(here::here(&quot;data&quot;, &quot;Download-GDPconstant-USD-countries.xls&quot;), # Excel filename
                sheet=&quot;Download-GDPconstant-USD-countr&quot;, # Sheet name
                skip=2) # Number of rows to skip</code></pre>
<p>Tidy the data, use billions for high values and change to shorter variable names.</p>
<pre class="r"><code># Pivot longer + Renaming indicators

tidy_GDP_data  &lt;- UN_GDP_data %&gt;% 
                      pivot_longer(cols = 4:51, names_to = &quot;Year&quot;) %&gt;% 
                      mutate(value=value/(1e9),
                             across(&#39;IndicatorName&#39;,str_replace,&quot;Exports of goods and services&quot;, &quot;Exports&quot;),
                             across(&#39;IndicatorName&#39;,str_replace,&quot;Imports of goods and services&quot;, &quot;Imports&quot;),
                             across(&#39;IndicatorName&#39;,str_replace,&quot;General government final consumption expenditure&quot;, &quot;Government expenditure&quot;),
                             across(&#39;IndicatorName&#39;,str_replace,&quot;Household consumption expenditure \\(including Non-profit institutions serving households\\)&quot;, &quot;Household expenditure&quot;))

# Let us compare GDP components for these 3 countries
country_list &lt;- c(&quot;United States&quot;,&quot;India&quot;, &quot;Germany&quot;)
indicator_list &lt;- c(&quot;Exports&quot;,&quot;Imports&quot;,&quot;Government expenditure&quot;,&quot;Household expenditure&quot;,&quot;Gross capital formation&quot;,&quot;Net Exports&quot;)</code></pre>
<div id="can-you-produce-the-plots-shown-in-class" class="section level2">
<h2>Can you produce the plots shown in class?</h2>
<pre class="r"><code>#Creating line chart and setting colors due to different order

tidy_GDP_data %&gt;% 
    mutate(Year=as.integer(Year)) %&gt;% 
    filter(Country %in% country_list, IndicatorName %in% indicator_list) %&gt;% 
    ggplot(aes(Year,value,color=IndicatorName))+
    geom_line(size=0.8)+
    xlim(1970,2017)+
    facet_wrap(~Country)+
    labs(title = &quot;GDP components over time&quot;,
       subtitle = &quot;In Constant 2010 USD&quot;,
       x=NULL,
       y=&quot;Billion US$&quot;,
       color= &quot;Components of GDP&quot;)+
    #scale_color_discrete(name = &quot;Components of GDP&quot;)+
   # theme(legend.title = &quot;Components of GDP&quot;)+
    scale_color_manual(values = c(&quot;#A3A500&quot;,
                                  &quot;#00BF7D&quot;,
                                  &quot;#F8766D&quot;,
                                  &quot;#2FBEF7&quot;,
                                  &quot;#EA7DF4&quot;))+
  theme_bw()+
  theme(panel.grid.minor.x = element_blank())+
  theme(text = element_text(size = 7))</code></pre>
<p><img src="/blogs/homework3_files/figure-html/gdp1_self-1.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code># Going back to wider to easily calculate columns

tidy_GDP_data %&gt;% 
    mutate(Year=as.integer(Year)) %&gt;% 
    filter(Country %in% country_list, IndicatorName %in% indicator_list) %&gt;% 
    select(Country,IndicatorName,Year,value) %&gt;% 
    pivot_wider(names_from = IndicatorName,values_from = value) %&gt;% 
    clean_names() %&gt;%   
    mutate(net_export=(exports-imports),
           GDP=(household_expenditure+ government_expenditure+gross_capital_formation+net_export),
           &quot;Household expenditure&quot;=household_expenditure/GDP,
           &quot;Government expenditure&quot;=government_expenditure/GDP,
           &quot;Gross capital formation&quot;=gross_capital_formation/GDP,
           &quot;Net Exports&quot;=net_export/GDP)%&gt;% 
    pivot_longer(cols=3:13,names_to = &quot;IndicatorName&quot;) %&gt;% 
    filter(IndicatorName %in% indicator_list) %&gt;% 
    ggplot(aes(year,value,color=IndicatorName,group=IndicatorName))+
    geom_line(size=0.8)+
    xlim(1970,2017)+
    facet_wrap(~country)+
    labs(title = &quot;GDP and its breakdown at constant 2010 prices in US Dollars&quot;,
       x=NULL,
       y=&quot;proportion&quot;,
       caption = &quot;Source: United Nations, https://unstats.un.org/unsd/snaama/Downloads&quot;)+
     scale_color_discrete(name = NULL)+
    theme_bw() +
    theme(panel.grid.minor.x = element_blank())+
    scale_y_continuous(labels = scales::percent)+
    theme(text = element_text(size = 7))</code></pre>
<p><img src="/blogs/homework3_files/figure-html/gdp2_self-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="what-is-this-last-chart-telling-you-can-you-explain-in-a-couple-of-paragraphs-the-different-dynamic-among-these-three-countries" class="section level2">
<h2>What is this last chart telling you? Can you explain in a couple of paragraphs the different dynamic among these three countries?</h2>
<p>The last chart potrays that Household expendiure has been the major contributor to GDP since 1970 in all the three countries, while net exports contributes the least.<br />
</p>
<p>While in Germany and the United States Gross Capital Formation and Government Expenditure have been almost overlapping, in India, Gross Capital Formation has been evidently higher than the Government Expenditure.<br />
</p>
<p>It is also interesting to note that in India, the proportion of contribution of Household Expenditure has been consistently falling while that of Gross Capital Formation has been increasing.</p>
</div>
<div id="what-is-the-difference-between-what-you-calculated-as-gdp-and-the-gdp-figure-included-in-the-dataframe" class="section level2">
<h2>What is the % difference between what you calculated as GDP and the GDP figure included in the dataframe?</h2>
<pre class="r"><code># Add column for self-made GDP and add column for percentage difference 

GDP_cal&lt;- tidy_GDP_data %&gt;% 
    mutate(Year=as.integer(Year)) %&gt;% 
    filter(Country %in% country_list) %&gt;% 
    pivot_wider(names_from = IndicatorName,values_from = value) %&gt;% 
    clean_names() %&gt;%   
    mutate(net_export=(exports-imports),
           GDP=(household_expenditure+ government_expenditure+gross_capital_formation+net_export),
           gdp_difference=(GDP-gross_domestic_product_gdp)/(GDP))

# Plot it
 
 GDP_cal%&gt;% ggplot(aes(x=year, y=gdp_difference))+
           geom_path()+
          geom_point(size=0.01)+
          facet_wrap(~country)+
          scale_y_continuous(labels = scales::percent)+
          labs(x=&quot;Year&quot;,
               y=&quot;Difference in GDP&quot;,
               title = &quot;% difference in given GDP and calculated GDP&quot; )+
          theme_bw()+
          theme(panel.grid.minor.x =element_blank())</code></pre>
<p><img src="/blogs/homework3_files/figure-html/gdp_self_made-1.png" width="100%" style="display: block; margin: auto;" />
<strong>Answer:</strong><br />
</p>
<p>It is interesting to note that since 2000, especially for Germany and US the value calculated by formula almost exactly matches the official GDP.</p>
</div>
</div>
<div id="deliverables" class="section level1">
<h1>Deliverables</h1>
<p>There is a lot of explanatory text, comments, etc. You do not need these, so delete them and produce a stand-alone document that you could share with someone. Knit the edited and completed R Markdown file as an HTML document (use the “Knit” button at the top of the script editor window) and upload it to Canvas.</p>
</div>
<div id="details" class="section level1">
<h1>Details</h1>
<ul>
<li>Who did you collaborate with: <em>Vani Duggal, Mehak Khanna, Manon Pillot, Nick Chen, Liyang Zhang, Tobias Delago</em></li>
<li>Approximately how much time did you spend on this problem set: <em>15h</em></li>
<li>What, if anything, gave you the most trouble: <em>Understanding the hypothesis workflow when doing it the first time</em></li>
</ul>
<p><strong>Please seek out help when you need it,</strong> and remember the <a href="https://mam2022.netlify.app/syllabus/#the-15-minute-rule" target="_blank">15-minute rule</a>. You know enough R (and have enough examples of code from class and your readings) to be able to do this. If you get stuck, ask for help from others, post a question on Slack– and remember that I am here to help too!</p>
<blockquote>
<p>As a true test to yourself, do you understand the code you submitted and are you able to explain it to someone else?</p>
</blockquote>
</div>
<div id="rubric" class="section level1">
<h1>Rubric</h1>
<p>Check minus (1/5): Displays minimal effort. Doesn’t complete all components. Code is poorly written and not documented. Uses the same type of plot for each graph, or doesn’t use plots appropriate for the variables being analyzed.</p>
<p>Check (3/5): Solid effort. Hits all the elements. No clear mistakes. Easy to follow (both the code and the output).</p>
<p>Check plus (5/5): Finished all components of the assignment correctly and addressed both challenges. Code is well-documented (both self-documented and with additional comments as necessary). Used tidyverse, instead of base R. Graphs and tables are properly labelled. Analysis is clear and easy to follow, either because graphs are labeled clearly or you’ve written additional text to describe how you interpret the output.</p>
</div>
